default_language_version:
    python: python3.8

repos: 
- repo: https://github.com/psf/black 
  rev: 23.9.1 
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.291
  hooks:
    - id: ruff