default:
    config_string: "fire"
    config_list: [1, 2, 3]
    config_none: None
    config_dict:
        sub_config: "water"
    mydate@template(datetimenow):
    mynumber%math: 2+3*8
    myuuid#uuid4:

        