name: publish

on:
  push:
    paths:
      - "dicfg/_version.py"

jobs:
  call-tests:
    uses: ./.github/workflows/tests.yml

  call-pypi:
    needs: call-tests
    uses: ./.github/workflows/pypi.yml

  call-release:
    needs: call-pypi
    uses: ./.github/workflows/release.yml
