name: publish

on:
  push:
    paths:
      - "dicfg/_version.py"

jobs:
  call-tests:
    uses: ./.github/workflows/tests.yml

  call-deploy_pypi:
    needs: call-run_tests
    uses: ./.github/workflows/pypi.yml

  call-create_github_release:
    needs: call-deploy_pypi
    uses: ./.github/workflows/release.yml
