name: Tests

on:
  push:
    paths:
      - "dicfg/**"
      - "tests/**"
      - .github/workflows/tests.yml
  pull_request:
    paths:
      - "dicfg/**"
      - "tests/**"
      - .github/workflows/tests.yml

jobs:
  call-reusable_tests:
    uses: ./.github/workflows/run_tests.yml
